'use strict';
// Kuratierte Datenbank bekannter Drittanbieter-Dienste.
// Handgepflegt (keine externe Lizenz nötig), Fokus: die im Web — und speziell
// auf deutschsprachigen Seiten — am häufigsten anzutreffenden Dienste.
// Kein Anspruch auf Vollständigkeit; Unbekanntes wird als 'unknown' geführt.
globalThis.WW = globalThis.WW || {};

(() => {
  const E = (id, name, owner, cat, dom, info) => ({ id, name, owner, cat, dom, info });

  WW.TRACKER_ENTITIES = [
    // ── Werbung & Tracking ────────────────────────────────────────────────
    E('google-ads', 'Google Ads / DoubleClick', 'Google (Alphabet)', 'advertising',
      ['doubleclick.net', 'googlesyndication.com', 'googleadservices.com',
        'adservice.google.com', 'googletagservices.com', 'adtrafficquality.google',
        'admob.com', 'app-measurement.com'],
      'Das größte Werbenetzwerk der Welt. Verfolgt Nutzer über Millionen von Websites und verknüpft die Daten mit Google-Konten und -Suchen.'),
    E('meta-pixel', 'Meta Pixel / Facebook', 'Meta (Facebook)', 'advertising',
      ['facebook.net', 'facebook.com', 'fbcdn.net', 'fbsbx.com'],
      'Das Facebook-Pixel meldet Seitenbesuche und Aktionen (z. B. Käufe) an Meta — Medienberichten und Anhörungen zufolge auch von Menschen ohne Facebook-Konto („Schattenprofile").'),
    E('amazon-ads', 'Amazon Advertising', 'Amazon', 'advertising',
      ['amazon-adsystem.com', 'amazon.dev'],
      'Amazons Werbenetzwerk; verknüpft Surfverhalten mit dem, was Amazon ohnehin über Kaufverhalten weiß.'),
    E('microsoft-ads', 'Microsoft Advertising (Bing Ads)', 'Microsoft', 'advertising',
      ['bat.bing.com', 'ads.microsoft.com', 'msads.net'],
      'Microsofts Werbe- und Conversion-Tracking, u. a. über das „UET-Tag" auf vielen Shopping-Seiten.'),
    E('criteo', 'Criteo', 'Criteo S.A.', 'advertising',
      ['criteo.com', 'criteo.net'],
      'Retargeting-Spezialist: sorgt dafür, dass dich angesehene Produkte als Werbung durchs Web „verfolgen".'),
    E('taboola', 'Taboola', 'Taboola', 'advertising',
      ['taboola.com', 'taboolasyndication.com'],
      'Liefert die „Das könnte Sie auch interessieren"-Kacheln unter Artikeln und trackt das Leseverhalten über viele Nachrichtenseiten.'),
    E('outbrain', 'Outbrain', 'Outbrain (Teads)', 'advertising',
      ['outbrain.com', 'outbrainimg.com'],
      'Wie Taboola: Empfehlungs-Werbung unter Artikeln, mit seitenübergreifendem Interessen-Tracking.'),
    E('xandr', 'Xandr / AppNexus', 'Microsoft', 'advertising',
      ['adnxs.com', 'adnxs-simple.com', 'xandr.com'],
      'Große Werbebörse (Ad Exchange); wickelt Echtzeit-Auktionen um Werbeplätze ab und synchronisiert dabei Nutzer-IDs.'),
    E('pubmatic', 'PubMatic', 'PubMatic', 'advertising',
      ['pubmatic.com'],
      'Werbebörse auf Verlagsseite; beteiligt an Echtzeit-Auktionen und Cookie-Syncing.'),
    E('magnite', 'Magnite / Rubicon', 'Magnite', 'advertising',
      ['rubiconproject.com', 'magnite.com'],
      'Eine der größten Werbebörsen auf Verlagsseite (früher Rubicon Project).'),
    E('openx', 'OpenX', 'OpenX', 'advertising',
      ['openx.net'],
      'Werbebörse mit Echtzeit-Auktionen und ID-Abgleich.'),
    E('indexexchange', 'Index Exchange', 'Index Exchange', 'advertising',
      ['casalemedia.com', 'indexww.com'],
      'Werbebörse; die Domain casalemedia.com taucht auf sehr vielen werbefinanzierten Seiten auf.'),
    E('sovrn', 'Sovrn (Lijit)', 'Sovrn Holdings', 'advertising',
      ['lijit.com', 'sovrn.com'],
      'Werbebörse und Affiliate-Technik für Publisher.'),
    E('tradedesk', 'The Trade Desk', 'The Trade Desk', 'advertising',
      ['adsrvr.org'],
      'Große Einkaufsplattform für Werbetreibende; betreibt mit „Unified ID" einen Cookie-Nachfolger auf E-Mail-Basis.'),
    E('mediamath', 'MediaMath', 'MediaMath (Infillion)', 'advertising',
      ['mathtag.com'],
      'Werbe-Einkaufsplattform mit Nutzer-Tracking über mathtag.com.'),
    E('adform', 'Adform', 'Adform (DK)', 'advertising',
      ['adform.net', 'adformdsp.net'],
      'Europäische Werbeplattform, auf deutschen Seiten häufig.'),
    E('equativ', 'Equativ (Smart AdServer)', 'Equativ (FR)', 'advertising',
      ['smartadserver.com', 'sascdn.com'],
      'Europäischer Ad-Server; liefert Anzeigen aus und zählt Einblendungen pro Nutzer.'),
    E('adition', 'ADITION', 'Virtual Minds / Ströer (DE)', 'advertising',
      ['adition.com', 'html-load.com', 'ad-delivery.net'],
      'Deutscher Ad-Server, Teil der Ströer-Gruppe; auf vielen deutschen Verlagsseiten.'),
    E('yieldlove', 'Yieldlove', 'Ströer (DE)', 'advertising',
      ['yieldlove.com', 'yieldlove-ad-serving.net'],
      'Deutscher Vermarktungsdienstleister, der für Publisher Werbe-Auktionen orchestriert.'),
    E('adscale', 'AdScale / Ströer', 'Ströer (DE)', 'advertising',
      ['adscale.de', 'stroeerdigitalgroup.de', 'stroeerdigitalmedia.de', 'stroeerws.de'],
      'Werbevermarktung der Ströer-Gruppe (u. a. t-online.de).'),
    E('tiktok-ads', 'TikTok Pixel', 'ByteDance (CN)', 'advertising',
      ['tiktok.com', 'tiktokcdn.com', 'tiktokv.com'],
      'TikToks Werbe-Tracking meldet Seitenbesuche und Käufe an ByteDance; datenschutzrechtlich wegen möglicher Zugriffe aus China umstritten.'),
    E('snap-ads', 'Snap Pixel', 'Snap Inc.', 'advertising',
      ['sc-static.net', 'snapchat.com'],
      'Conversion-Tracking von Snapchat.'),
    E('pinterest-ads', 'Pinterest Tag', 'Pinterest', 'advertising',
      ['pinterest.com', 'pinimg.com'],
      'Pinterests Besuchs- und Kauf-Tracking.'),
    E('linkedin-ads', 'LinkedIn Insight', 'Microsoft', 'advertising',
      ['ads.linkedin.com', 'linkedin.com', 'licdn.com'],
      'B2B-Tracking: meldet LinkedIn, welche Firmenwebsites und Fachartikel du besuchst — bei Login direkt deinem Profil zuordenbar.'),
    E('twitter-ads', 'X/Twitter Ads', 'X Corp.', 'advertising',
      ['ads-twitter.com', 't.co'],
      'Conversion-Tracking von X (Twitter); t.co ist zugleich der Link-Verkürzer, über den X alle Klicks mitzählt.'),
    E('quantcast', 'Quantcast', 'Quantcast', 'advertising',
      ['quantserve.com', 'quantcount.com'],
      'Reichweitenmessung und Werbe-Targeting; misst Publikumsprofile über viele Websites.'),
    E('teads', 'Teads', 'Teads', 'advertising',
      ['teads.tv'],
      'Video-Werbung in Artikeln („Outstream"), mit Sichtbarkeits- und Nutzer-Tracking.'),
    E('adroll', 'AdRoll', 'NextRoll', 'advertising',
      ['adroll.com'],
      'Retargeting-Dienst für Shops.'),
    E('bidswitch', 'BidSwitch', 'Criteo', 'advertising',
      ['bidswitch.net'],
      'Drehscheibe zwischen Werbebörsen; taucht fast nur zum ID-Abgleich (Cookie-Syncing) auf.'),
    E('yieldlab', 'Yieldlab', 'Virtual Minds / Ströer (DE)', 'advertising',
      ['yieldlab.net', 'yieldlab.com'],
      'Deutsche Werbebörse (Virtual Minds); auf sehr vielen deutschen Verlagsseiten an den Anzeigen-Auktionen beteiligt.'),
    E('plista', 'plista', 'plista GmbH (DE)', 'advertising',
      ['plista.com'],
      'Deutscher Empfehlungswerbe-Dienst („Das könnte Sie interessieren") mit Leseverhaltens-Tracking.'),
    E('ias', 'Integral Ad Science', 'IAS', 'advertising',
      ['adsafeprotected.com', 'integralads.com'],
      'Werbe-Verifizierung: prüft, ob Anzeigen sichtbar waren und in welchem Umfeld — misst dafür detailliert das Seitengeschehen.'),
    E('doubleverify', 'DoubleVerify', 'DoubleVerify', 'advertising',
      ['doubleverify.com', 'dv.tech'],
      'Werbe-Verifizierung wie IAS; misst Sichtbarkeit und Umfeld von Anzeigen.'),
    E('moat', 'Moat (Oracle)', 'Oracle', 'advertising',
      ['moatads.com'],
      'Werbe-Sichtbarkeitsmessung von Oracle.'),
    E('reddit-ads', 'Reddit (Pixel/Einbettungen)', 'Reddit', 'advertising',
      ['reddit.com', 'redditstatic.com', 'redditmedia.com'],
      'Reddits Conversion-Pixel meldet Seitenbesuche an Reddit; auch eingebettete Beiträge laden von diesen Domains.'),
    E('yandex', 'Yandex Metrica/Ads', 'Yandex (RU)', 'analytics',
      ['yandex.ru', 'yandex.com', 'ymetrica.com', 'webvisor.org'],
      'Russischer Analyse- und Werbedienst inkl. Session-Replay („Webvisor"); Datenfluss nach Russland.'),

    // ── Datenhändler & ID-Abgleich ───────────────────────────────────────
    E('adobe-audience', 'Adobe Audience Manager', 'Adobe', 'audience',
      ['demdex.net', 'everesttech.net', 'omtrdc.net', '2o7.net'],
      'Adobes Daten- und Analyseplattform großer Konzerne; demdex.net dient dem seitenübergreifenden ID-Abgleich.'),
    E('adobe-experience', 'Adobe Experience Cloud', 'Adobe', 'analytics',
      ['adobe.io', 'adobedc.net', 'adobe.com'],
      'Adobes Marketing- und Analyseplattform: Das Web-SDK („Alloy") sendet Besuchsdaten und Kennungen über adobedc.net und die adobe.io-Schnittstellen an Adobe; auf großen Firmen- und Shop-Seiten sehr verbreitet.'),
    E('adobe-launch', 'Adobe Launch (Tag-Manager)', 'Adobe', 'tagmanager',
      ['adobedtm.com'],
      'Adobes Tag-Manager: lädt und steuert weitere Mess- und Werbeskripte der Experience Cloud nach.'),
    E('liveramp', 'LiveRamp', 'LiveRamp', 'audience',
      ['rlcdn.com', 'pippio.com', 'liveramp.com'],
      'Einer der größten Identitäts-Vermittler: verknüpft Online-Kennungen mit realen Personen- und Offline-Daten.'),
    E('id5', 'ID5', 'ID5 (EU)', 'audience',
      ['id5-sync.com'],
      'Europäischer „Universal-ID"-Dienst — eine gemeinsame Nutzerkennung für viele Werbefirmen als Cookie-Ersatz.'),
    E('utiq', 'Utiq', 'Deutsche Telekom, Vodafone, Orange, Telefónica', 'audience',
      ['utiq.com', 'utiqcontent.com'],
      'Von europäischen Mobilfunkanbietern gegründeter Dienst, der Nutzer anhand der Mobilfunkverbindung wiedererkennt („Netzbetreiber-Tracking") — nur mit Einwilligung, aber besonders weitreichend.'),
    E('netid', 'netID', 'European netID Foundation (RTL, ProSiebenSat.1, United Internet)', 'audience',
      ['netid.de'],
      'Login-Allianz deutscher Medienkonzerne: ein Konto für viele Seiten, samt zentralem „Einwilligungsspeicher" — laut Selbstbeschreibung auch als anbieterübergreifende Kennung für Werbezwecke gedacht (Cookie-Ersatz, einwilligungsbasiert).'),
    E('emetriq', 'emetriq', 'Deutsche Telekom (DE)', 'audience',
      ['emetriq.de', 'emetriq.com', 'xplosion.de'],
      'Datenvermarkter der Deutschen Telekom; sammelt und verknüpft Profildaten für zielgerichtete Werbung auf deutschen Seiten.'),
    E('oracle-data', 'Oracle Data Cloud (BlueKai/AddThis)', 'Oracle', 'audience',
      ['bluekai.com', 'addthis.com', 'addthisedge.com'],
      'Ehemals einer der größten Datenhändler; AddThis-Buttons dienten jahrelang zugleich der Datensammlung. (Dienst eingestellt, Reste noch verbreitet.)'),
    E('salesforce-krux', 'Salesforce Audience (Krux)', 'Salesforce', 'audience',
      ['krxd.net'],
      'Daten-Management-Plattform: sammelt und segmentiert Besucherprofile für Vermarkter.'),
    E('lotame', 'Lotame', 'Lotame', 'audience',
      ['crwdcntrl.net'],
      'Daten-Management-Plattform mit ID-Abgleich (crwdcntrl = „crowd control").'),
    E('theadex', 'The ADEX', 'Virtual Minds / Ströer (DE)', 'audience',
      ['theadex.com'],
      'Deutsche Daten-Management-Plattform; sammelt und segmentiert Besucherprofile für Vermarkter.'),
    E('permutive', 'Permutive', 'Permutive', 'audience',
      ['permutive.com', 'permutive.app'],
      'Publisher-Datenplattform: baut aus dem Leseverhalten Zielgruppen-Segmente für die Werbevermarktung.'),
    E('neustar', 'Neustar/TransUnion', 'TransUnion', 'audience',
      ['agkn.com'],
      'Identitäts- und Marketingdaten des Auskunftei-Konzerns TransUnion.'),
    E('scorecard', 'comScore', 'comScore', 'audience',
      ['scorecardresearch.com', 'comscore.com'],
      'Reichweiten- und Publikumsmessung über sehr viele Websites hinweg (Marktforschung).'),
    E('nielsen', 'Nielsen', 'Nielsen', 'audience',
      ['imrworldwide.com'],
      'Markt- und Mediaforschung; misst Mediennutzung seitenübergreifend.'),

    // ── Sitzungsaufzeichnung ─────────────────────────────────────────────
    E('hotjar', 'Hotjar', 'Contentsquare', 'session',
      ['hotjar.com', 'hotjar.io'],
      'Zeichnet Mausbewegungen, Klicks und Scrollen auf und erstellt Heatmaps; Formulareingaben können mitgeschnitten werden.'),
    E('clarity', 'Microsoft Clarity', 'Microsoft', 'session',
      ['clarity.ms'],
      'Kostenloses Session-Replay von Microsoft; laut eigenen Nutzungsbedingungen darf Microsoft die erhobenen Daten auch für eigene Zwecke (u. a. Produktverbesserung und KI) verwenden.'),
    E('fullstory', 'FullStory', 'FullStory', 'session',
      ['fullstory.com'],
      'Detailliertes Session-Replay inklusive „Rage Clicks"-Analyse.'),
    E('mouseflow', 'Mouseflow', 'Mouseflow', 'session',
      ['mouseflow.com'],
      'Session-Replay und Formular-Analyse (misst z. B., bei welchem Feld Nutzer abbrechen).'),
    E('smartlook', 'Smartlook', 'Cisco', 'session',
      ['smartlook.com', 'smartlook.cloud'],
      'Session-Replay für Web und Apps.'),
    E('logrocket', 'LogRocket', 'LogRocket', 'session',
      ['logrocket.io', 'logrocket.com', 'lr-ingest.io', 'lr-in.com', 'lr-in-prod.com'],
      'Session-Replay mit technischem Fokus (Fehlersuche), zeichnet dennoch das Nutzerverhalten auf.'),
    E('luckyorange', 'Lucky Orange', 'Lucky Orange', 'session',
      ['luckyorange.com', 'luckyorange.net'],
      'Heatmaps, Session-Replay und Live-Besucherbeobachtung.'),
    E('crazyegg', 'Crazy Egg', 'Crazy Egg', 'session',
      ['crazyegg.com'],
      'Heatmap- und Scroll-Analyse.'),
    E('contentsquare', 'Contentsquare', 'Contentsquare', 'session',
      ['contentsquare.net', 'contentsquare.com'],
      'Enterprise-Verhaltensanalyse: zeichnet Interaktionen detailliert auf und aggregiert sie zu „Experience Analytics".'),

    // ── Statistik & Analyse ──────────────────────────────────────────────
    E('bazaarvoice', 'Bazaarvoice', 'Bazaarvoice (Marlin Equity)', 'analytics',
      ['bazaarvoice.com'],
      'Liefert Bewertungen und Kundenfotos in Shops aus und misst dabei, wer welche Produkte ansieht; der Anbieter vermarktet diese Daten auch für Werbezwecke.'),
    E('google-analytics', 'Google Analytics', 'Google (Alphabet)', 'analytics',
      ['google-analytics.com', 'analytics.google.com'],
      'Das mit Abstand verbreitetste Analyse-Werkzeug. Die Besuchsdaten fließen an Google und können dort mit anderen Google-Daten zusammengeführt werden.'),
    E('gtm', 'Google Tag Manager', 'Google (Alphabet)', 'tagmanager',
      ['googletagmanager.com'],
      'Googles Tag-Manager: lädt und steuert weitere Tracking-Skripte. Die Anfragen direkt danach zeigen, was er gestartet hat.'),
    E('tealium', 'Tealium (Tag-Manager)', 'Tealium', 'tagmanager',
      ['tiqcdn.com'],
      'Tag-Manager großer Marken: lädt und steuert von tiqcdn.com aus weitere Tracking-Skripte und verteilt Besuchsdaten an angebundene Dienste.'),
    E('matomo-cloud', 'Matomo Cloud', 'InnoCraft (NZ)', 'analytics',
      ['matomo.cloud', 'innocraft.cloud'],
      'Gehostete Variante des Open-Source-Tools Matomo; datenschutzfreundlicher als Google Analytics, Daten liegen aber beim Dienstleister.'),
    E('etracker', 'etracker', 'etracker GmbH (DE)', 'analytics',
      ['etracker.com', 'etracker.de'],
      'Deutscher Analysedienst, wirbt mit einwilligungsfreiem, cookielosem Tracking.'),
    E('mapp', 'Mapp Intelligence (Webtrekk)', 'Mapp (DE)', 'analytics',
      ['webtrekk.net', 'mapp.com', 'wt-eu02.net', 'wt-safetag.com', 'mateti.net'],
      'Deutscher Enterprise-Analysedienst (früher Webtrekk), auf großen deutschen Seiten verbreitet.'),
    E('infonline', 'INFOnline / IVW-Messung', 'INFOnline GmbH (DE)', 'analytics',
      ['ioam.de', 'iocnt.net', 'infonline.de'],
      'Die offizielle deutsche Reichweitenmessung (IVW/agma) auf nahezu allen deutschen Medienseiten; misst standardisiert Besucherzahlen.'),
    E('piwikpro', 'Piwik PRO', 'Piwik PRO (PL)', 'analytics',
      ['piwik.pro'],
      'Europäische Analyse-Suite mit Datenschutz-Fokus, beliebt bei Behörden.'),
    E('plausible', 'Plausible', 'Plausible (EE)', 'analytics',
      ['plausible.io'],
      'Minimalistischer, cookieloser EU-Analysedienst — Beispiel für datensparsame Statistik.'),
    E('fathom', 'Fathom Analytics', 'Fathom (CA)', 'analytics',
      ['usefathom.com'],
      'Cookieloser Analysedienst mit Datenschutz-Fokus.'),
    E('mixpanel', 'Mixpanel', 'Mixpanel', 'analytics',
      ['mixpanel.com', 'mxpnl.com'],
      'Produkt-Analytics: verfolgt einzelne Nutzeraktionen (Events) sehr detailliert, oft mit Nutzer-IDs.'),
    E('amplitude', 'Amplitude', 'Amplitude', 'analytics',
      ['amplitude.com'],
      'Produkt-Analytics mit detaillierten Nutzerprofilen und Ereignisketten.'),
    E('segment', 'Segment', 'Twilio', 'analytics',
      ['segment.com', 'segment.io', 'segmentapis.com'],
      'Daten-Drehscheibe: sammelt Nutzerereignisse einmal ein und verteilt sie an beliebig viele angeschlossene Dienste weiter.'),
    E('heap', 'Heap', 'Contentsquare', 'analytics',
      ['heapanalytics.com'],
      'Zeichnet pauschal alle Interaktionen auf („autocapture"), Auswertung erfolgt später.'),
    E('chartbeat', 'Chartbeat', 'Chartbeat', 'analytics',
      ['chartbeat.com', 'chartbeat.net'],
      'Echtzeit-Statistik für Redaktionen (wer liest gerade was, wie weit wird gescrollt).'),
    E('parsely', 'Parse.ly', 'Automattic', 'analytics',
      ['parsely.com'],
      'Inhalte-Analyse für Verlage.'),
    E('statcounter', 'StatCounter', 'StatCounter', 'analytics',
      ['statcounter.com'],
      'Einfacher Besucherzähler, seit den 2000ern verbreitet.'),
    E('piano', 'Piano / AT Internet', 'Piano Software', 'analytics',
      ['piano.io', 'tinypass.com', 'xiti.com', 'aticdn.net'],
      'Paywall- und Analyseplattform vieler Verlage (tinypass steuert Bezahlschranken, xiti/AT Internet misst Besuche).'),
    E('optimizely', 'Optimizely', 'Optimizely', 'analytics',
      ['optimizely.com'],
      'A/B-Testing: teilt Besucher in Gruppen und misst, welche Seitenvariante besser „funktioniert".'),
    E('vwo', 'VWO', 'Wingify', 'analytics',
      ['vwo.com', 'visualwebsiteoptimizer.com', 'wingify.com'],
      'A/B-Testing und Verhaltensmessung.'),
    E('abtasty', 'AB Tasty', 'AB Tasty (FR)', 'analytics',
      ['abtasty.com'],
      'Europäisches A/B-Testing mit Besucher-Segmentierung.'),
    E('kameleoon', 'Kameleoon', 'Kameleoon (DE/FR)', 'analytics',
      ['kameleoon.com', 'kameleoon.eu'],
      'A/B-Testing und Personalisierung, in DACH verbreitet.'),
    E('simpleanalytics', 'Simple Analytics', 'Simple Analytics (NL)', 'analytics',
      ['simpleanalytics.com', 'simpleanalyticscdn.com'],
      'Cookieloser EU-Analysedienst mit Datenschutz-Fokus.'),
    E('wpcom', 'WordPress.com / Jetpack', 'Automattic', 'analytics',
      ['wp.com'],
      'Jetpack-Dienste für WordPress-Seiten: Besucherzähler (stats.wp.com) und Bild-Auslieferung.'),
    E('baidu', 'Baidu Analytics', 'Baidu (CN)', 'analytics',
      ['baidu.com'],
      'Chinesischer Analysedienst; Datenfluss nach China.'),
    E('newrelic', 'New Relic', 'New Relic', 'errortracking',
      ['newrelic.com', 'nr-data.net'],
      'Leistungsüberwachung: misst Ladezeiten und Fehler aus Sicht echter Besucher.'),
    E('datadog', 'Datadog RUM', 'Datadog', 'errortracking',
      ['datadoghq.com', 'datadoghq-browser-agent.com', 'browser-intake-datadoghq.com', 'browser-intake-datadoghq.eu'],
      'Leistungs- und Fehlerüberwachung („Real User Monitoring").'),
    E('cf-insights', 'Cloudflare Insights', 'Cloudflare', 'analytics',
      ['cloudflareinsights.com'],
      'Cookielose Besuchsstatistik von Cloudflare.'),

    // ── Fehler-Tracking ──────────────────────────────────────────────────
    E('sentry', 'Sentry', 'Functional Software', 'errortracking',
      ['sentry.io', 'sentry-cdn.com'],
      'Meldet JavaScript-Fehler samt Browser-Details und letzten Aktionen („Breadcrumbs") an den Betreiber.'),
    E('bugsnag', 'Bugsnag', 'SmartBear', 'errortracking',
      ['bugsnag.com'],
      'Fehler-Meldedienst.'),
    E('rollbar', 'Rollbar', 'Rollbar', 'errortracking',
      ['rollbar.com'],
      'Fehler-Meldedienst.'),
    E('appinsights', 'Azure Application Insights', 'Microsoft', 'errortracking',
      ['visualstudio.com', 'monitor.azure.com', 'applicationinsights.azure.com'],
      'Microsofts Leistungs- und Fehlerüberwachung (dc.services.visualstudio.com).'),
    E('dynatrace', 'Dynatrace', 'Dynatrace', 'errortracking',
      ['dynatrace.com'],
      'Enterprise-Leistungsüberwachung mit Real-User-Monitoring.'),
    E('pingdom', 'Pingdom RUM', 'SolarWinds', 'errortracking',
      ['pingdom.net'],
      'Ladezeit-Messung aus Besuchersicht.'),

    // ── Soziale Netzwerke & Einbettungen ─────────────────────────────────
    E('youtube', 'YouTube', 'Google (Alphabet)', 'social',
      ['youtube.com', 'ytimg.com', 'googlevideo.com'],
      'Eingebettete Videos melden Google den Seitenbesuch und setzen teils Cookies — schon beim Laden, vor jedem Klick.'),
    E('youtube-nc', 'YouTube (erweiterter Datenschutzmodus)', 'Google (Alphabet)', 'social',
      ['youtube-nocookie.com'],
      'Die „nocookie"-Einbettung setzt erst beim Abspielen Cookies — datensparsamer, aber der Abruf geht weiterhin an Google.'),
    E('instagram', 'Instagram', 'Meta (Facebook)', 'social',
      ['instagram.com', 'cdninstagram.com'],
      'Eingebettete Instagram-Beiträge melden Meta den Besuch.'),
    E('twitter-embed', 'X/Twitter Einbettungen', 'X Corp.', 'social',
      ['twitter.com', 'x.com', 'twimg.com'],
      'Eingebettete Tweets laden Skripte von X und melden den Seitenbesuch.'),
    E('vimeo', 'Vimeo', 'Vimeo', 'social',
      ['vimeo.com', 'vimeocdn.com'],
      'Videoplattform; eingebettete Player übertragen Besuchsdaten an Vimeo.'),
    E('disqus', 'Disqus', 'Zeta Global', 'social',
      ['disqus.com', 'disquscdn.com'],
      'Kommentarsystem; gehört dem Marketing-Konzern Zeta Global und wurde öffentlich wiederholt für sein Werbe-Tracking kritisiert.'),
    E('addtoany', 'AddToAny', 'AddToAny', 'social',
      ['addtoany.com'],
      'Teilen-Buttons für viele Netzwerke.'),
    E('gravatar', 'Gravatar', 'Automattic', 'social',
      ['gravatar.com'],
      'Globale Profilbilder (v. a. in Blog-Kommentaren); der Abruf verrät Gravatar, welche Seiten du liest.'),
    E('whatsapp', 'WhatsApp', 'Meta (Facebook)', 'social',
      ['whatsapp.com', 'whatsapp.net'],
      '„Per WhatsApp teilen"-Buttons und Chat-Links laden von Meta-Servern und melden den Besuch.'),
    E('twitch', 'Twitch', 'Amazon', 'social',
      ['twitch.tv', 'ttvnw.net', 'jtvnw.net'],
      'Eingebettete Twitch-Streams melden Amazon den Seitenbesuch.'),
    E('spotify', 'Spotify', 'Spotify (SE)', 'social',
      ['spotify.com', 'scdn.co'],
      'Eingebettete Player melden Spotify den Seitenbesuch.'),
    E('soundcloud', 'SoundCloud', 'SoundCloud (DE)', 'social',
      ['soundcloud.com', 'sndcdn.com'],
      'Eingebettete Player melden SoundCloud den Seitenbesuch.'),

    // ── Marketing & Kundenbindung ────────────────────────────────────────
    E('gorgias', 'Gorgias (Support-Chat)', 'Gorgias', 'marketing',
      ['gorgias.chat'],
      'Support-Chat für Online-Shops. Das Widget lädt auf jeder Seite mit und erkennt wiederkehrende Kundinnen und Kunden.'),
    E('rebuy', 'Rebuy', 'Rebuy, LLC', 'marketing',
      ['rebuyengine.com'],
      'Personalisiert Produktempfehlungen und Zusatzangebote in Shopify-Shops und wertet dafür das Verhalten im Shop aus.'),
    E('clerk-io', 'Clerk.io', 'Clerk.io (DK)', 'marketing',
      ['clerk.io'],
      'Liefert Suche und Produktempfehlungen für Shops und wertet dafür aus, was Besucher suchen und ansehen.'),
    E('hubspot', 'HubSpot', 'HubSpot', 'marketing',
      ['hubspot.com', 'hs-scripts.com', 'hs-analytics.net', 'hsforms.com', 'hsappstatic.net', 'hubapi.com', 'usemessages.com'],
      'CRM- und Marketing-Plattform: verfolgt Besucher und verknüpft sie beim ersten Formular mit Name und E-Mail.'),
    E('mailchimp', 'Mailchimp', 'Intuit', 'marketing',
      ['chimpstatic.com', 'list-manage.com', 'mailchimp.com'],
      'Newsletter-Dienst; Links in Newslettern tragen persönliche Kennungen.'),
    E('klaviyo', 'Klaviyo', 'Klaviyo', 'marketing',
      ['klaviyo.com'],
      'E-Commerce-Marketing: verbindet Surfverhalten im Shop mit E-Mail-Profilen.'),
    E('braze', 'Braze', 'Braze', 'marketing',
      ['braze.com', 'braze.eu', 'appboy.com'],
      'Kundenbindungs-Plattform (Push, E-Mail, In-App) mit Nutzerprofilen.'),
    E('onesignal', 'OneSignal', 'OneSignal', 'marketing',
      ['onesignal.com'],
      'Push-Benachrichtigungsdienst; vergibt Gerätekennungen.'),
    E('emarsys', 'Emarsys', 'SAP', 'marketing',
      ['emarsys.net', 'scarabresearch.com'],
      'Marketing-Automatisierung von SAP; „Scarab" ist das Web-Tracking dazu.'),
    E('intercom', 'Intercom', 'Intercom', 'functional',
      ['intercom.io', 'intercomcdn.com'],
      'Chat-Widget; legt schon beim Laden ein Besucherprofil an.'),
    E('zendesk', 'Zendesk', 'Zendesk', 'functional',
      ['zendesk.com', 'zdassets.com', 'zopim.com'],
      'Support- und Chat-System.'),
    E('tawk', 'tawk.to', 'tawk.to', 'functional',
      ['tawk.to'],
      'Kostenloses Chat-Widget.'),
    E('drift', 'Drift', 'Salesloft', 'marketing',
      ['drift.com', 'driftt.com'],
      'Vertriebs-Chat mit Besucher-Tracking und Firmen-Erkennung.'),
    E('brevo', 'Brevo (Sendinblue)', 'Brevo (FR)', 'marketing',
      ['brevo.com', 'sendinblue.com', 'sibforms.com'],
      'Europäischer Newsletter- und Marketing-Dienst.'),
    E('cleverreach', 'CleverReach', 'CleverReach (DE)', 'marketing',
      ['cleverreach.com'],
      'Deutscher Newsletter-Dienst; Links tragen Empfänger-Kennungen.'),
    E('cleverpush', 'CleverPush', 'CleverPush (DE)', 'marketing',
      ['cleverpush.com'],
      'Deutscher Push-Benachrichtigungsdienst; vergibt Geräte-Kennungen.'),

    // ── Affiliate ────────────────────────────────────────────────────────
    E('awin', 'AWIN', 'Axel Springer (DE)', 'affiliate',
      ['awin1.com', 'awin.com', 'dwin1.com', 'zanox.com'],
      'Großes europäisches Affiliate-Netzwerk (ehem. Zanox); verfolgt Klicks von Empfehlungslinks bis zum Kauf.'),
    E('cj', 'CJ Affiliate', 'Publicis', 'affiliate',
      ['emjcd.com', 'cj.com', 'anrdoezrs.net', 'tkqlhce.com', 'dpbolvw.net'],
      'Eines der ältesten Affiliate-Netzwerke (Commission Junction).'),
    E('tradedoubler', 'Tradedoubler', 'Tradedoubler (SE)', 'affiliate',
      ['tradedoubler.com'],
      'Europäisches Affiliate-Netzwerk.'),
    E('adcell', 'Adcell', 'Firstlead GmbH (DE)', 'affiliate',
      ['adcell.de', 'adcell.com'],
      'Deutsches Affiliate-Netzwerk.'),

    // ── Consent-Management ───────────────────────────────────────────────
    E('onetrust', 'OneTrust / Cookielaw', 'OneTrust', 'cmp',
      ['onetrust.com', 'cookielaw.org', 'onetrust.io', 'onetrust.eu'],
      'Weit verbreiteter Cookie-Banner-Dienst; speichert deine Einwilligungs-Entscheidung.'),
    E('usercentrics', 'Usercentrics', 'Usercentrics (DE)', 'cmp',
      ['usercentrics.eu', 'usercentrics.com'],
      'Deutscher Cookie-Banner-Dienst, auf deutschsprachigen Seiten sehr häufig.'),
    E('cookiebot', 'Cookiebot', 'Usercentrics (DE)', 'cmp',
      ['cookiebot.com'],
      'Cookie-Banner-Dienst mit automatischem Website-Scan.'),
    E('sourcepoint', 'Sourcepoint', 'Sourcepoint', 'cmp',
      ['sourcepoint.com', 'sp-prod.net', 'summerhamster.com', 'privacy-mgmt.com'],
      'Consent-Plattform großer Verlage (u. a. hinter vielen „Pur-Abo oder Tracking"-Bannern).'),
    E('consentmanager', 'consentmanager', 'consentmanager (DE/SE)', 'cmp',
      ['consentmanager.net', 'consentmanager.de', 'delivery.consentmanager.net'],
      'Cookie-Banner-Dienst, in DACH verbreitet.'),
    E('didomi', 'Didomi', 'Didomi (FR)', 'cmp',
      ['didomi.io', 'privacy-center.org'],
      'Französische Consent-Plattform.'),
    E('iubenda', 'iubenda', 'iubenda (IT)', 'cmp',
      ['iubenda.com'],
      'Cookie-Banner- und Datenschutztext-Dienst, auf kleineren Seiten sehr verbreitet.'),
    E('cookieyes', 'CookieYes', 'CookieYes', 'cmp',
      ['cookieyes.com'],
      'Cookie-Banner-Dienst.'),
    E('termly', 'Termly', 'Termly', 'cmp',
      ['termly.io'],
      'Cookie-Banner- und Rechtstext-Dienst.'),

    // ── CDN & Infrastruktur ──────────────────────────────────────────────
    E('jquery-cdn', 'jQuery CDN', 'OpenJS Foundation', 'cdn',
      ['jquery.com'],
      'Liefert die weit verbreitete JavaScript-Bibliothek jQuery aus. Reine Auslieferung — der Abruf verrät aber IP-Adresse und besuchte Seite.'),
    E('shopify', 'Shopify', 'Shopify (CA)', 'cdn',
      ['shopify.com', 'myshopify.com'],
      'Shop-Plattform hinter vielen Online-Läden; liefert Seiten und Skripte aus und sieht dabei Besuche und Bestellungen im Shop.'),
    E('cloudflare', 'Cloudflare', 'Cloudflare', 'cdn',
      ['cloudflare.com', 'cloudflare.net', 'cdnjs.com', 'challenges.cloudflare.com'],
      'Riesiges Infrastruktur-Netz (CDN, Schutzdienste, Turnstile-Captcha); ein erheblicher Teil des Webs läuft über Cloudflare.'),
    E('akamai', 'Akamai', 'Akamai', 'cdn',
      ['akamai.net', 'akamaized.net', 'akamaihd.net', 'edgesuite.net', 'edgekey.net'],
      'Eines der ältesten und größten CDNs.'),
    E('fastly', 'Fastly', 'Fastly', 'cdn',
      ['fastly.net', 'fastlylb.net'],
      'CDN, u. a. hinter großen Nachrichten-Seiten.'),
    E('aws', 'Amazon Web Services', 'Amazon', 'cdn',
      ['amazonaws.com', 'cloudfront.net', 'awsstatic.com', 'media-amazon.com', 'ssl-images-amazon.com'],
      'Amazons Cloud; CloudFront-Subdomains gehören jeweils einem Kunden — welcher Dienst dahintersteckt, ist von außen schwer erkennbar.'),
    E('azure-cdn', 'Microsoft Azure', 'Microsoft', 'cdn',
      ['azureedge.net', 'msecnd.net', 'azure.com'],
      'Microsofts Cloud-CDN.'),
    E('google-fonts', 'Google Fonts', 'Google (Alphabet)', 'cdn',
      ['fonts.googleapis.com', 'fonts.gstatic.com'],
      'Schriften von Google-Servern. Schon der Abruf übermittelt deine IP-Adresse an Google — deutsche Gerichte (LG München 2022) sahen darin ohne Einwilligung einen DSGVO-Verstoß.'),
    E('google-cdn', 'Google APIs / Hosted Libraries', 'Google (Alphabet)', 'cdn',
      ['googleapis.com', 'gstatic.com', 'googleusercontent.com', 'ggpht.com'],
      'Googles Auslieferungs-Infrastruktur für Skripte, Bibliotheken und Inhalte (ggpht.com liefert z. B. YouTube-Profilbilder).'),
    E('jsdelivr', 'jsDelivr', 'jsDelivr (Open Source)', 'cdn',
      ['jsdelivr.net'],
      'Kostenloses Open-Source-CDN für JavaScript-Bibliotheken.'),
    E('unpkg', 'unpkg', 'Cloudflare (gesponsert)', 'cdn',
      ['unpkg.com'],
      'CDN für npm-Pakete.'),
    E('typekit', 'Adobe Fonts (Typekit)', 'Adobe', 'cdn',
      ['typekit.net', 'typekit.com'],
      'Schriften-Dienst von Adobe; Abrufe werden pro Seite gezählt.'),
    E('bootstrapcdn', 'BootstrapCDN', 'jsDelivr', 'cdn',
      ['bootstrapcdn.com'],
      'CDN für das Bootstrap-Framework.'),
    E('bunny', 'bunny.net', 'BunnyWay (SI)', 'cdn',
      ['bunny.net', 'b-cdn.net'],
      'Europäisches CDN.'),
    E('fontawesome', 'Font Awesome', 'Fonticons', 'cdn',
      ['fontawesome.com'],
      'Icon-Schriftarten; der Abruf verrät IP und besuchte Seite.'),
    E('imgix', 'imgix', 'imgix', 'cdn',
      ['imgix.net'],
      'Bild-CDN mit Echtzeit-Bildbearbeitung.'),
    E('cloudinary', 'Cloudinary', 'Cloudinary', 'cdn',
      ['cloudinary.com'],
      'Bild- und Video-CDN.'),
    E('polyfill', 'polyfill.io', '(übernommen, Vorsicht)', 'cdn',
      ['polyfill.io'],
      'Ehemals verbreitetes Skript-CDN — 2024 wurde es nach einem Eigentümerwechsel laut Sicherheitsforschern für die Auslieferung von Schadcode an zigtausende Websites missbraucht. Lehrbeispiel, warum Fremd-Skripte ein Risiko sind.'),

    // ── Funktionale Dienste ──────────────────────────────────────────────
    E('equally-ai', 'Equally AI', 'Equally AI', 'functional',
      ['equally.ai'],
      'Barrierefreiheits-Widget, das Seiten nachträglich anpassen soll. Es lädt auf jeder Unterseite mit und übermittelt dabei die aufgerufene Adresse.'),
    E('haendlerbund', 'Händlerbund', 'Händlerbund e. V. (DE)', 'functional',
      ['haendlerbund.de'],
      'Liefert Gütesiegel und Rechtstexte für Online-Shops aus; der Abruf des Siegels meldet den Seitenaufruf an den Händlerbund.'),
    E('bfarm-versandhandel', 'Versandhandelsregister (BfArM)', 'Bundesinstitut für Arzneimittel und Medizinprodukte', 'functional',
      ['dimdi.de'],
      'Amtliches Versandhandelsregister: Apotheken binden von hier das Sicherheitslogo ein, das ihre Zulassung belegt.'),
    E('recruitee', 'Recruitee', 'Tellent (NL)', 'functional',
      ['recruitee.com', 'recruiteecdn.com'],
      'Bewerbungsportal, das Stellenanzeigen und Bewerbungsformulare in Firmenseiten einbettet und Bewerbungen entgegennimmt.'),
    E('indeed-apply', 'Indeed', 'Indeed', 'functional',
      ['indeed.com'],
      'Stellenbörse; das eingebettete Bewerbungsformular überträgt Bewerbungsdaten an Indeed und zeigt dort an, welche Stellen angesehen wurden.'),
    E('ziggeo', 'Ziggeo', 'Ziggeo', 'functional',
      ['ziggeo.com'],
      'Dienst für Video-Aufnahme und -Wiedergabe im Browser, etwa für Video-Bewerbungen; aufgenommene Videos laufen über die Server des Anbieters.'),
    E('stripe', 'Stripe', 'Stripe', 'functional',
      ['stripe.com', 'stripe.network'],
      'Bezahldienst. Das Stripe-Skript sammelt zur Betrugserkennung detaillierte Gerätedaten — oft auf allen Seiten, nicht nur beim Bezahlen.'),
    E('paypal', 'PayPal', 'PayPal', 'functional',
      ['paypal.com', 'paypalobjects.com'],
      'Bezahldienst mit Betrugserkennung und Gerätedaten-Erfassung.'),
    E('klarna', 'Klarna', 'Klarna (SE)', 'functional',
      ['klarna.com', 'klarnaservices.com'],
      'Bezahldienst („Kauf auf Rechnung"); prüft dabei Bonitäts- und Gerätedaten.'),
    E('recaptcha', 'Google reCAPTCHA', 'Google (Alphabet)', 'functional',
      ['recaptcha.net'],
      'Bot-Schutz von Google: bewertet anhand von Verhalten und Browserdaten, ob du ein Mensch bist — und übermittelt dabei umfangreiche Daten an Google.'),
    E('hcaptcha', 'hCaptcha', 'Intuition Machines', 'functional',
      ['hcaptcha.com'],
      'Captcha-Alternative mit Datenschutz-Versprechen.'),
    E('googlemaps', 'Google Maps', 'Google (Alphabet)', 'functional',
      ['maps.googleapis.com', 'maps.gstatic.com'],
      'Eingebettete Karten; der Abruf meldet Google Besuch und Kartenausschnitt.'),
    E('openstreetmap', 'OpenStreetMap', 'OSM Foundation', 'functional',
      ['openstreetmap.org', 'tile.openstreetmap.org'],
      'Freie Karten-Alternative; überträgt IP und Kartenausschnitt an die OSM-Server.'),
    E('mapbox', 'Mapbox', 'Mapbox', 'functional',
      ['mapbox.com'],
      'Kartendienst; überträgt IP, Kartenausschnitt und Nutzungsstatistiken.'),
    E('algolia', 'Algolia', 'Algolia', 'functional',
      ['algolia.net', 'algolianet.com'],
      'Suchfunktion vieler Websites — jede Sucheingabe geht an Algolia-Server.'),
    E('trustpilot', 'Trustpilot', 'Trustpilot (DK)', 'functional',
      ['trustpilot.com'],
      'Bewertungs-Widget; meldet den Seitenbesuch an Trustpilot.'),
    E('trustindex', 'Trustindex', 'Trustindex (HU)', 'functional',
      ['trustindex.io'],
      'Bewertungs-Widgets („Google-Sterne" u. a.) zum Einbetten; der Abruf meldet Trustindex den Seitenbesuch.'),
    E('trustedshops', 'Trusted Shops', 'Trusted Shops (DE)', 'functional',
      ['trustedshops.com', 'trustedshops.de', 'etrusted.com'],
      'Deutsches Gütesiegel-Widget in vielen Online-Shops.'),
    E('mollie', 'Mollie', 'Mollie (NL)', 'functional',
      ['mollie.com'],
      'Europäischer Bezahldienst.'),
    E('adyen', 'Adyen', 'Adyen (NL)', 'functional',
      ['adyen.com'],
      'Europäischer Bezahldienst mit Betrugserkennung (Gerätedaten).'),
    E('crisp', 'Crisp', 'Crisp (FR)', 'functional',
      ['crisp.chat'],
      'Chat-Widget; legt beim Laden ein Besucherprofil an.'),
    E('userlike', 'Userlike', 'Userlike (DE)', 'functional',
      ['userlike.com'],
      'Deutsches Chat-Widget.'),
    E('jwplayer', 'JW Player', 'JWP', 'functional',
      ['jwplayer.com', 'jwpcdn.com', 'jwpltx.com'],
      'Video-Player vieler Nachrichtenseiten; jwpltx.com sammelt Abspiel-Telemetrie.'),
    E('brightcove', 'Brightcove', 'Brightcove', 'functional',
      ['brightcove.com', 'brightcove.net'],
      'Video-Plattform mit Abspiel-Statistiken.'),
    E('arkose', 'Arkose Labs (FunCaptcha)', 'Arkose Labs', 'functional',
      ['arkoselabs.com', 'funcaptcha.com'],
      'Captcha-/Bot-Schutz auf Login-Seiten; erfasst Verhaltens- und Gerätedaten.'),
    E('datadome', 'DataDome', 'DataDome (FR)', 'functional',
      ['captcha-delivery.com', 'datadome.co'],
      'Bot-Erkennung: bewertet anhand von Verhaltens- und Gerätedaten, ob ein Besucher echt ist.'),
    E('awswaf', 'AWS WAF Captcha', 'Amazon', 'functional',
      ['awswaf.com'],
      'Amazons Bot-Schutz-Captcha.'),
    E('radware-bot', 'Radware Bot Manager', 'Radware', 'functional',
      ['perfdrive.com'],
      'Bot-Erkennung (ehemals ShieldSquare).'),
    E('google-login', 'Google-Konto / Login', 'Google (Alphabet)', 'functional',
      ['accounts.google.com'],
      '„Mit Google anmelden"-Widgets; der Abruf verrät Google den Seitenbesuch, bei bestehendem Login samt Kontobezug.'),

    // ── Verlags-/Betreiber-Infrastruktur (eigene CDNs unter anderer Domain) ─
    E('dm-eigene', 'dm (eigene Auslieferung)', 'dm-drogerie markt', 'cdn',
      ['dm.de', 'dmtech.com', 'dm-static.com'],
      'Technik-Domains von dm selbst: Produktbilder, Suche und Empfehlungen für dm.de. Die Daten bleiben beim Anbieter der Seite.'),
    E('bild-cdn', 'BILD (eigene Auslieferung)', 'Axel Springer (DE)', 'cdn',
      ['bild.de', 'bildstatic.de'],
      'Eigene Bild- und Skript-Domains der BILD.'),
    E('computerbild-cdn', 'COMPUTER BILD (eigene Auslieferung)', 'Axel Springer (DE)', 'cdn',
      ['computerbild.de', 'computer-bild.de'],
      'Eigene Auslieferungs-Domains der COMPUTER BILD.'),
    E('axelspringer-infra', 'Axel Springer Infrastruktur', 'Axel Springer (DE)', 'cdn',
      ['axelspringer.de'],
      'Konzern-Infrastruktur der Axel-Springer-Titel.'),
    E('asadcdn', 'Axel Springer Werbe-CDN', 'Axel Springer (DE)', 'advertising',
      ['asadcdn.com'],
      'Werbemittel-Auslieferung der Axel-Springer-Titel (BILD, WELT …).'),
    E('burdaforward-infra', 'BurdaForward Infrastruktur', 'BurdaForward (DE)', 'cdn',
      ['focus.de', 'chip.de', 'burda-forward.de', 'bfops.io'],
      'Verlags-Infrastruktur von BurdaForward (Focus, Chip …).'),
    E('bf-ad', 'BurdaForward Werbung', 'BurdaForward (DE)', 'advertising',
      ['bf-ad.net'],
      'Werbe-Auslieferung der BurdaForward-Titel.'),
    E('united-internet', 'United Internet (web.de/GMX)', 'United Internet / 1&1 (DE)', 'cdn',
      ['web.de', 'gmx.net', 'ui-portal.de', 'uicdn.com'],
      'Eigene Portale und Auslieferungs-Domains von United Internet.'),
    E('ebay-infra', 'eBay (eigene Auslieferung)', 'eBay', 'cdn',
      ['ebay.de', 'ebay.com', 'ebayimg.com', 'ebaystatic.com'],
      'eBays eigene Bild-, Skript- und Telemetrie-Domains.'),
    E('adevinta', 'Adevinta (mobile.de/Kleinanzeigen)', 'Adevinta', 'cdn',
      ['mobile.de', 'kleinanzeigen.de', 'classistatic.de'],
      'Auslieferungs-Domains der Adevinta-Kleinanzeigenportale.'),
    E('scout24', 'Scout24 (eigene Auslieferung)', 'Scout24 (DE)', 'cdn',
      ['immobilienscout24.de', 'static-immobilienscout24.de'],
      'Eigene Auslieferungs-Domains von ImmobilienScout24.'),
    E('wettercom-cdn', 'wetter.com (eigene Auslieferung)', 'wetter.com / ProSiebenSat.1 (DE)', 'cdn',
      ['wetter.com', 'wettercomassets.com'],
      'Eigene Auslieferungs-Domains von wetter.com.'),
    E('wbd', 'Warner Bros. Discovery (CNN/Max)', 'Warner Bros. Discovery', 'cdn',
      ['cnn.com', 'cnn.io', 'max.com'],
      'Konzern-Infrastruktur von CNN und Max.'),
    E('greenvideo', 'SuperNext (GreenVideo)', 'SuperNext GmbH (DE)', 'cdn',
      ['greenvideo.io'],
      'Video-/Podcast-Plattform („Medienbetriebssystem") deutscher Verlagsseiten; liefert eingebettete Player und Streams aus.'),
    E('cloudimage', 'Cloudimage', 'Scaleflex', 'cdn',
      ['cloudimg.io'],
      'Bild-CDN mit Echtzeit-Optimierung.'),
    E('zalando-cdn', 'Zalando (eigene Auslieferung)', 'Zalando (DE)', 'cdn',
      ['zalando.de', 'ztat.net'],
      'Zalandos eigene Bild- und Skript-Domains.'),
    E('voxmedia', 'Vox Media Infrastruktur', 'Vox Media', 'cdn',
      ['voxmedia.com', 'vox-cdn.com'],
      'Verlags-Infrastruktur von Vox Media (The Verge u. a.).'),
    E('anthropic', 'Anthropic (Claude)', 'Anthropic', 'cdn',
      ['anthropic.com', 'claude.ai'],
      'Eigene API- und Auslieferungs-Domains von Anthropic für Claude (claude.ai).'),

    // ── Weitere Ad-Tech aus der Feld-Erhebung ────────────────────────────
    E('btloader', 'Blockthrough', 'Blockthrough', 'advertising',
      ['btloader.com'],
      'Liefert Werbung aus, die Adblocker-Nutzern trotz Blocker angezeigt wird („Acceptable Ads"-Programm), und erkennt dafür Adblock-Nutzung.'),
    E('concert', 'Concert (Vox Media)', 'Vox Media', 'advertising',
      ['concert.io'],
      'Werbe-Marktplatz von Vox Media (The Verge u. a.).'),
    E('brightline', 'BrightLine', 'BrightLine', 'advertising',
      ['brightline.tv'],
      'Interaktive TV-/Streaming-Werbung.'),
    E('bombora', 'Bombora', 'Bombora', 'audience',
      ['ml314.com', 'bombora.com'],
      'B2B-Datenanbieter: erfasst, welche Fachthemen in welchen Firmen gelesen werden, und bietet diese „Kaufabsichts"-Daten als Produkt an.'),
    E('cxense', 'Cxense (Piano DMP)', 'Piano Software', 'audience',
      ['cxense.com'],
      'Leseverhaltens-Datenplattform vieler Verlage, heute Teil von Piano.'),
    E('mux', 'Mux Data', 'Mux', 'analytics',
      ['litix.io', 'mux.com'],
      'Video-Abspiel-Telemetrie (Qualität, Abbrüche, Sehdauer).'),
    E('mediamelon', 'MediaMelon', 'MediaMelon', 'analytics',
      ['mediamelon.com'],
      'Video-Abspiel-Telemetrie und Streaming-Optimierung.'),
    E('varify', 'Varify', 'Varify (DE)', 'analytics',
      ['varify.io'],
      'Deutsches A/B-Testing-Werkzeug.'),
    E('auth0', 'Auth0', 'Okta', 'functional',
      ['auth0.com'],
      'Login-Dienst („Anmelden mit …"); wickelt die Anmeldung über Okta-Server ab.'),
    E('zephr', 'Zephr', 'Zuora', 'functional',
      ['zephr.com'],
      'Paywall-Steuerung: entscheidet, wer wie viele Artikel frei lesen darf.'),
    E('conversant', 'Conversant (Fastclick)', 'Conversant / Publicis', 'advertising',
      ['fastclick.net', 'conversantmedia.com'],
      'Werbenetzwerk (ehemals ValueClick/Fastclick).'),
    E('coral', 'Coral (Kommentare)', 'Vox Media', 'social',
      ['coralproject.net'],
      'Open-Source-Kommentarsystem, gehostet von Vox Media.'),
    E('wunderkind', 'Wunderkind', 'Wunderkind (ehem. BounceX)', 'marketing',
      ['wknd.ai', 'bounceexchange.com'],
      'Marketing-Dienst, der abspringende Besucher erkennt und mit E-Mail-/Popup-Kampagnen zurückholen soll.'),
  ];

  // Pfad-Hinweise für Domains, die sich nicht pauschal zuordnen lassen
  // (z. B. google.com/google.de: Suche, aber auch Werbe-Endpunkte).
  WW.PATH_HINTS = [
    { hostRe: /(^|\.)google\.(com|de|[a-z]{2,3})$/, pathRe: /^\/(pagead|ads|ccm\/collect|ads\/measurement)/, entityId: 'google-ads' },
    { hostRe: /(^|\.)google\.(com|de|[a-z]{2,3})$/, pathRe: /^\/recaptcha\//, entityId: 'recaptcha' },
    { hostRe: /(^|\.)google\.(com|de|[a-z]{2,3})$/, pathRe: /^\/maps\//, entityId: 'googlemaps' },
    { hostRe: /(^|\.)google\.[a-z.]{2,6}$/, pathRe: /^\/(gen_204|log|js\/)/, entityId: 'google-cdn' },
    { hostRe: /(^|\.)bing\.com$/, pathRe: /^\/(action|bat)/, entityId: 'microsoft-ads' },
  ];

  // Stand der mitgelieferten Liste. Eine nachgeladene Fassung wird nur
  // übernommen, wenn ihr Stand jünger ist (siehe dbupdate.js).
  WW.TRACKER_DB_STAND = '2026-08-05';
  WW.TRACKER_DB_QUELLE = 'mitgeliefert';

  // Nachschlage-Index: Domain → Entity. Längster (spezifischster) Treffer
  // gewinnt, weil vom vollen Hostnamen aus Suffix für Suffix gesucht wird.
  // Wird neu aufgebaut, wenn eine aktualisierte Liste eingespielt wurde.
  const MAP = new Map();
  const BY_ID = new Map();
  WW.rebuildTrackerIndex = function rebuildTrackerIndex() {
    MAP.clear();
    BY_ID.clear();
    for (const ent of WW.TRACKER_ENTITIES) {
      for (const d of ent.dom) MAP.set(d, ent);
      BY_ID.set(ent.id, ent);
    }
  };
  WW.rebuildTrackerIndex();

  // host (+ optional Pfad) → Entity oder null
  WW.classifyHost = function classifyHost(host, path) {
    if (!host) return null;
    if (path) {
      for (const h of WW.PATH_HINTS) {
        if (h.hostRe.test(host) && h.pathRe.test(path)) return BY_ID.get(h.entityId) || null;
      }
    }
    const labels = host.split('.');
    for (let i = 0; i <= labels.length - 2; i++) {
      const ent = MAP.get(labels.slice(i).join('.'));
      if (ent) return ent;
    }
    return null;
  };

  WW.entityById = (id) => BY_ID.get(id) || null;
})();
